#!/usr/bin/env python3

import json
from pathlib import Path

def load_json_file(filename):
    """Load and return JSON data from a file."""
    with open(filename, 'r', encoding='utf-8') as f:
        return json.load(f)

def write_blocklist_conf(output_file, sources):
    """Write the blocklist configuration file."""
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('##################################################################################\n')
        f.write('# DNSCrypt-Proxy Domains Blocklist Configuration\n')
        f.write('# Generated by generate_domains_blocklist_conf.py\n')
        f.write('##################################################################################\n\n')

        # Local additions
        f.write('# Local additions\n')
        f.write('file:domains-blocklist-local-additions.txt\n\n')

        # Process each source
        for source_name, categories in sources.items():
            f.write(f'# {source_name} Blocklists\n')
            f.write(f'# Source: {categories["source_url"]}\n\n')

            for category, data in categories["categories"].items():
                f.write(f'# {category}\n')
                if "description" in data:
                    f.write(f'# {data["description"]}\n')
                
                for blocklist in data["blocklists"]:
                    f.write(f'# {blocklist["name"]}\n')
                    if "count" in blocklist:
                        f.write(f'# Entries: {blocklist["count"]}\n')
                    f.write(f'{blocklist["url"]}\n\n')

def main():
    """Main function to generate the domains-blocklist.conf file."""
    print("Starting to generate domains-blocklist.conf...")

    # Define sources and their JSON files
    sources = {
        "RethinkDNS": {
            "file": "blocklists_rethinkdns.json",
            "source_url": "https://rethinkdns.com/configure"
        },
        "ShadowWhisperer": {
            "file": "blocklists_shadowwhisperer.json",
            "source_url": "https://github.com/ShadowWhisperer/BlockLists"
        },
        "The Firebog": {
            "file": "blocklists_firebog.json",
            "source_url": "https://firebog.net/"
        },
        "Geoffrey Frogeye": {
            "file": "blocklists_frogeye.json",
            "source_url": "https://hostfiles.frogeye.fr/"
        }
    }

    # Load data from each source
    blocklist_data = {}
    for source_name, info in sources.items():
        try:
            data = load_json_file(info["file"])
            data["source_url"] = info["source_url"]
            blocklist_data[source_name] = data
            print(f"Loaded {info['file']}")
        except FileNotFoundError:
            print(f"Warning: {info['file']} not found, skipping {source_name} blocklists")
        except json.JSONDecodeError:
            print(f"Error: {info['file']} is not valid JSON, skipping {source_name} blocklists")

    # Generate the configuration file
    output_file = "domains-blocklist.conf"
    write_blocklist_conf(output_file, blocklist_data)
    print(f"Successfully generated {output_file}")

if __name__ == "__main__":
    main() 